### ISSUE TITLE
Ja support

### ISSUE THREAD

**Issue by sakurw** [hsohliyt105/py-fumen#7]
Japanese is not encoded correctly.
but tetris-fumen can be successfully encoded.
comment in fumen：てすと@1205dsafｆさｆさ５３２５４２！；
encoded_fumen：https://knewjade.github.io/fumen-for-mobile/#?d=v115@9gilEeR4glRpDeR4wwg0RpCeBtxwi0DeBtwwJeAgWQ?ClnjRA4pjvB2XbBBF0eRA51D9BzHO6Alx2sBRbcHBkNkuDl?XOSAiGMRB2XbBBF0eRA5vD9BGos6BFEqRAFtLRBxXwHBlXO?SACFkUB1XjBCFjHSA5sD9BGoU3BlFhRAlJ8yBDYwHBlXOSA?CFkUB0XjBCFjHSAZrD9BGoU3BF0eRAlJ8yBDYozB

**Comment by hsohliyt105** [comment]
for me it looks like its working fine.

```
from py_fumen import encode, decode

pages = decode("v115@9gilEeR4glRpDeR4wwg0RpCeBtxwi0DeBtwwJeAgWj?Blvs2AWxDfEToHVBlvs2AWkg6ASoPmDzCXTAVa2EB2XHDBw?vnRAVa2EB2XHDBwvnRAVau6A1XPDCGKjRAVau6AyXPDCGqn?RAVau6A0XPDCG6gRAVaW3AxXPDCG6MBA")

print(pages[0].comment)

fumen = encode(pages)

print(fumen)
```

which results in:
```
てすと@1205dsafｆさｆさ５３２５４２！；
v115@9gilEeR4glRpDeR4wwg0RpCeBtxwi0DeBtwwJeAgWj?Blvs2AWxDfEToHVBlvs2AWkg6ASoPmDzCXTAVa2EB2XHDBw?vnRAVa2EB2XHDBwvnRAVau6A1XPDCGKjRAVau6AyXPDCGqn?RAVau6A0XPDCG6gRAVaW3AxXPDCG6MBA
```

Maybe your environment's encoding is not utf-8.
Could you check your environment encoding?

Or could you add more detail?

**Comment by sakurw** [comment]
Thank you response
I ran the same code and found that the first print() is in unicode.
“%u3066%u3059%u3068@1205dsaf%uFF46%u3055%uFF46%u3055%uFF15%uFF13%uFF12%uFF15%uFF14%uFF12%uFF01%uFF1B”
In this case, the output is in unicode in the tet score, but should I change it to UTF-8 and put it in the comment?

Running in UTF-8 (bottom right of image)

![image](https://github.com/hsohliyt105/py-fumen/assets/45168417/879b808b-dda8-4aa1-a7a2-f65126c9ab97)

**Comment by hsohliyt105** [comment]
It looks like the comment is not unescaped correctly.
Try updating the py-fumen by pip, and if it doesnt work yet then, you can manually unescape with js_escape library in the py_fumen; example:
```
from py_fumen import js_escape

js_escape.unescape("%u3066%u3059%u3068@1205dsaf%uFF46%u3055%uFF46%u3055%uFF15%uFF13%uFF12%uFF15%uFF14%uFF12%uFF01%uFF1B")
```
->
```
てすと@1205dsafｆさｆさ５３２５４２！；
```

**Comment by sakurw** [comment]
I got this error when I tried to install it again
Is it related to the fact that part of the MIT license is expired?

`Collecting py-fumen
  Using cached py_fumen-0.1.5.tar.gz (15 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [71 lines of output]
  C:\Users\sakur\AppData\Local\Temp\pip-build-env-kyw9a252\overlay\Lib\site-packages\setuptools\config\_apply_pyprojecttoml.py:76: _MissingDynamic: `license` defined outside of `pyproject.toml` is ignored.
  !!
  
          ********************************************************************************
          The following seems to be defined outside of `pyproject.toml`:
  
          `license = 'MIT'`
  
          According to the spec (see the link below), however, setuptools CANNOT
          consider this value unless `license` is listed as `dynamic`.
  
          https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
  
          To prevent this problem, you can list `license` under `dynamic` or alternatively
          remove the `[project]` table from your file and rely entirely on other means of
          configuration.
          ********************************************************************************
  
  !!
    _handle_missing_dynamic(dist, project_table)
  C:\Users\sakur\AppData\Local\Temp\pip-build-env-kyw9a252\overlay\Lib\site-packages\setuptools\config\_apply_pyprojecttoml.py:76: _MissingDynamic: `keywords` defined outside of `pyproject.toml` is ignored.
  !!
  
          ********************************************************************************
          The following seems to be defined outside of `pyproject.toml`:
  
          `keywords = ['fumen']`
  
          According to the spec (see the link below), however, setuptools CANNOT
          consider this value unless `keywords` is listed as `dynamic`.
  
          https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
  
          To prevent this problem, you can list `keywords` under `dynamic` or alternatively
          remove the `[project]` table from your file and rely entirely on other means of
          configuration.
          ********************************************************************************
  
  !!
    _handle_missing_dynamic(dist, project_table)
  Traceback (most recent call last):
    File "C:\Users\sakur\PycharmProjects\tetr_replay_analysis\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\sakur\PycharmProjects\tetr_replay_analysis\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\sakur\PycharmProjects\tetr_replay_analysis\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\sakur\AppData\Local\Temp\pip-build-env-kyw9a252\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\sakur\AppData\Local\Temp\pip-build-env-kyw9a252\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "C:\Users\sakur\AppData\Local\Temp\pip-build-env-kyw9a252\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 5, in <module>
    File "C:\Users\sakur\AppData\Local\Temp\pip-build-env-kyw9a252\overlay\Lib\site-packages\setuptools\__init__.py", line 104, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\sakur\AppData\Local\Temp\pip-build-env-kyw9a252\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 158, in setup
      dist.parse_config_files()
    File "C:\Users\sakur\PycharmProjects\tetr_replay_analysis\venv\lib\site-packages\_virtualenv.py", line 21, in parse_config_files
      result = old_parse_config_files(self, *args, **kwargs)
    File "C:\Users\sakur\AppData\Local\Temp\pip-build-env-kyw9a252\overlay\Lib\site-packages\setuptools\dist.py", line 631, in parse_config_files
      pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
    File "C:\Users\sakur\AppData\Local\Temp\pip-build-env-kyw9a252\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 69, in apply_configuration
      return _apply(dist, config, filepath)
    File "C:\Users\sakur\AppData\Local\Temp\pip-build-env-kyw9a252\overlay\Lib\site-packages\setuptools\config\_apply_pyprojecttoml.py", line 57, in apply
      _apply_project_table(dist, config, root_dir)
    File "C:\Users\sakur\AppData\Local\Temp\pip-build-env-kyw9a252\overlay\Lib\site-packages\setuptools\config\_apply_pyprojecttoml.py", line 83, in _apply_project_table
      corresp(dist, value, root_dir)
    File "C:\Users\sakur\AppData\Local\Temp\pip-build-env-kyw9a252\overlay\Lib\site-packages\setuptools\config\_apply_pyprojecttoml.py", line 184, in _license
      _set_config(dist, "license", val["text"])
  KeyError: 'text'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1`

**Comment by hsohliyt105** [comment]
Sadly, the compiled library seems like it has deprecated dependencies with pyproject.toml.
And I cannot fix or compile and upload it again until July since I cannot access my computer.

Instead, you can temporarily fix the issue with a method on this stackoverflow post.

https://stackoverflow.com/questions/77523055/missingdynamic-license-defined-outside-of-pyproject-toml-is-ignored

**Comment by sakurw** [comment]
ok thanks
I used py-fumen-py and everything worked fine.
Thanks a lot for your lots of support.
